### ISSUE TITLE
Works locally but not in cloud deployments

### ISSUE THREAD

**Issue by brdemorin** [NathanChen198/streamlit-cookies-controller#6]
The title pretty much says it. Great component and works as expected for me locally but cookies do not set in any cloud deployment I have tried - docker or no docker. v1.35.0

**Comment by quantumalchemy** [comment]
Yeah just found this out  does not work only in localhost
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/app/bookem.py", line 29, in <module>
    if not auth.is_user_logged_in():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/authHandler.py", line 53, in is_user_logged_in
    return self.controller.get(self.cookie_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/streamlit_cookies_controller/cookie_controller.py", line 68, in get
    if name not in self.__cookies:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by xytian315** [comment]
I had the same error `TypeError: argument of type 'NoneType' is not iterable` it seems like it happened inconsistently though...

**Comment by kaizen63** [comment]
Happens here too when I run it in docker in aks. With every new image build I create a new login cookie key in th auth_cookie section.
First time I login to streamlit app the app crashes with this error.
